Konverter mellom nytt og gammelt format
navikt/hag-domene-inntektsmelding pull request #11
Opened 2024-01-15 09:38 UTC by mortenbyhring

Litt omstendelig kode, men kan forhåpentligvis komme til nytte

2024-01-15 15:11 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
Nå skannet jeg bare gjennom, men fikk litt overload av importstiene 😵 Kan vi heller importere alt fra en pakke med alias? F. eks. `ArbeidsgiverperiodeV1`.

Foreslår også å gjøre funksjonene om til extensions. Det vil gjøre det lettere å lese.

Når disse endringene enten er implementert eller avfeid så kan jeg kikke på ny 🔍

2024-01-22 07:53 UTC, mortenbyhring commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
Har skrevet om nå, så da skal det være klart for en ny titt

2024-01-23 14:44 UTC, bjerga requested changes

2024-01-23 14:44 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
> +            fullLønnIArbeidsgiverPerioden = if (this.agp?.redusertLoennIAgp == null) { null } else { this.agp.redusertLoennIAgp.convert() },
Tror det er bedre å bruke `FullLoennIArbeidsgiverPerioden(true, null, null)` istedenfor å returnere `null` basert på validering i https://github.com/navikt/helsearbeidsgiver-inntektsmelding/blob/9a16daf2781ec73fb7f84dc09f32dbdf01b93dc5/api/src/main/kotlin/no/nav/helsearbeidsgiver/inntektsmelding/api/innsending/InnsendingValidate.kt#L30.

Det eksisterer dog rader i databasen der `fullLønnIArbeidsgiverPerioden` er `null`.

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        bonus.convert() shouldBe BonusV1
Unødvendig variabel.

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        )
Rar formattering.

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        // konvertering setter inntektsdato til epoch-tid og naturalytelse til tom liste
> naturalytelse til tom liste

Hvorfor det?

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +                periode,
Disse bør være ulike.

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +    )
Ha argument på egne linjer.

2024-01-23 14:44 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +    val dato = LocalDate.of(2023, 1, 1)
```suggestion
```

2024-01-23 15:23 UTC, mortenbyhring commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
> +        // TODO (inntektsmelding.behandlingsdager != null) -- må legge inn støtte for dette i nytt format
Det stemmer, men feltet finnes i gammelt format, men brukes ikke - og det finnes ikke i det hele tatt i nytt format, så egentlig var det bare en huskelapp

2024-01-23 15:27 UTC, mortenbyhring commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        // konvertering setter inntektsdato til epoch-tid og naturalytelse til tom liste
naturalytelser er ikke nullable i nytt format, så da er ingen naturalytelser i gammel (null) lik, men ikke lik, tom liste

2024-01-23 15:29 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        // konvertering setter inntektsdato til epoch-tid og naturalytelse til tom liste
Aha, så ikke at naturalytelser var nullable.

2024-01-23 15:33 UTC, mortenbyhring commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        )
ja, vetta f hva som skjedde her

2024-01-24 08:53 UTC, mortenbyhring commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
> +            fullLønnIArbeidsgiverPerioden = if (this.agp?.redusertLoennIAgp == null) { null } else { this.agp.redusertLoennIAgp.convert() },
OK, så slik altså? 
fullLønnIArbeidsgiverPerioden = 
this.agp?.redusertLoennIAgp?.convert() ?: FullLoennIArbeidsgiverPerioden(true, null, null)

2024-01-24 13:54 UTC, bjerga commented on src/main/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/Utils.kt
> +            fullLønnIArbeidsgiverPerioden = if (this.agp?.redusertLoennIAgp == null) { null } else { this.agp.redusertLoennIAgp.convert() },
Det funker.

2024-01-24 14:00 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        gammelIM.shouldBeEqualToIgnoringFields(orginal, Inntektsmelding::inntektsdato, Inntektsmelding::naturalytelser, Inntektsmelding::fullLønnIArbeidsgiverPerioden, Inntektsmelding::forespurtData)
Hvorfor må `Inntektsmelding::fullLønnIArbeidsgiverPerioden` og `Inntektsmelding::forespurtData` ignoreres?

2024-01-24 14:14 UTC, mortenbyhring commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        gammelIM.shouldBeEqualToIgnoringFields(orginal, Inntektsmelding::inntektsdato, Inntektsmelding::naturalytelser, Inntektsmelding::fullLønnIArbeidsgiverPerioden, Inntektsmelding::forespurtData)
forespurtData trenger ikke å ignoreres! Jeg fikser.. 
Men fullLønnIAgp går fra null i gammel versjon, oversettes til nytt format, og oversettes så tilbake til:
FullLoennIArbeidsgiverPerioden(true, null, null) (det var det du ønsket i en annen kommentar)
Ja, jeg kunne startet med den samme verdien i gammel istedenfor null, men det er jo mer interessant å teste konvertering av null-verdi.. 
Siden testen oversetter først fra gammel til ny, og deretter tilbake til gammel, blir det sånn

2024-01-24 14:59 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +        gammelIM.shouldBeEqualToIgnoringFields(orginal, Inntektsmelding::inntektsdato, Inntektsmelding::naturalytelser, Inntektsmelding::fullLønnIArbeidsgiverPerioden, Inntektsmelding::forespurtData)
> Ja, jeg kunne startet med den samme verdien i gammel istedenfor null, men det er jo mer interessant å teste konvertering av null-verdi.. 

Men du sjekker vel ikke det, så da er ikke det heller testet?
Det minner meg på at alle felt som ignoreres burde ha en egen sjekk.

2024-01-26 08:49 UTC, bjerga commented on src/test/kotlin/no/nav/helsearbeidsgiver/domene/inntektsmelding/UtilsTest.kt
> +    }
Ville lagt til
```
gammelIm.inntektsdato shouldBe LocalDate.EPOCH
gammelIm.naturalytelser shouldBe emptyList()
gammelIm.fullLønnIArbeidsgiverPerioden shouldBe FullLoennIArbeidsgiverPerioden(true, null, null)
```

2024-01-26 09:35 UTC, bjerga approved these changes

2024-01-26 09:40 UTC, merged